"""Initial migration

Revision ID: 1533bfc72cc5
Revises:
Create Date: 2023-07-04 08:37:57.764647

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1533bfc72cc5"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order",
        sa.Column(
            "status",
            sa.Enum(
                "CANCELED",
                "PENDING_PAYMENT",
                "RECEIVED",
                "PREPARING",
                "READY",
                "WITHDRAWN",
                name="orderstatus",
            ),
            nullable=False,
        ),
        sa.Column("total_amount", sa.String(), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_order_uuid"), "order", ["uuid"], unique=True)
    op.create_table(
        "product",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "SANDWICH",
                "SIDE_DISH",
                "BEVERAGE",
                "DESSERT",
                name="productcategory",
            ),
            nullable=False,
        ),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("image", postgresql.BYTEA(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("uuid", sa.UUID(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_product_category"), "product", ["category"], unique=False)
    op.create_index(op.f("ix_product_uuid"), "product", ["uuid"], unique=True)
    op.create_table(
        "user",
        sa.Column("cpf", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("password", sa.String(), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=True),
        sa.Column("uuid", sa.UUID(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_cpf"), "user", ["cpf"], unique=True)
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_is_admin"), "user", ["is_admin"], unique=False)
    op.create_index(op.f("ix_user_uuid"), "user", ["uuid"], unique=True)
    op.create_table(
        "orderitem",
        sa.Column("comment", sa.String(), nullable=True),
        sa.Column("order_uuid", sa.UUID(), nullable=True),
        sa.Column("product_uuid", sa.UUID(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_uuid"],
            ["order.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["product_uuid"],
            ["product.uuid"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("orderitem")
    op.drop_index(op.f("ix_user_uuid"), table_name="user")
    op.drop_index(op.f("ix_user_is_admin"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_index(op.f("ix_user_cpf"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_product_uuid"), table_name="product")
    op.drop_index(op.f("ix_product_category"), table_name="product")
    op.drop_table("product")
    op.drop_index(op.f("ix_order_uuid"), table_name="order")
    op.drop_table("order")
    # ### end Alembic commands ###
