"""Update UserModel removing password and is_admin fields

Revision ID: e79e020b5ec4
Revises: 83e71a157092
Create Date: 2023-10-23 23:20:50.704147

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e79e020b5ec4"
down_revision = "83e71a157092"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "order",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index("ix_user_is_admin", table_name="user")
    op.drop_column("user", "password")
    op.drop_column("user", "is_admin")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("is_admin", sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "user", sa.Column("password", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.create_index("ix_user_is_admin", "user", ["is_admin"], unique=False)
    op.alter_column(
        "order",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###
