version: '3.7'

services:
  app:
    build: .
    container_name: my-food-app
    depends_on:
      - db
    image: my-food-app:latest
    ports:
      - 8000:8000
    volumes:
      - source: .
        target: /src
        type: bind
    command: bash init_app.sh

  db:
    container_name: my-food-db
    image: postgres:14
    env_file: .env
    ports:
      - 5432:5432
