version: '3.7'

services:
  app:
    build: .
    container_name: my-food-app
    depends_on:
      - db
    image: my-food-app:latest
    ports:
      - 8000:8000
    volumes:
      - source: .
        target: /app
        type: bind
    command: uvicorn my_food.adapters.FastAPI.main:app --host 0.0.0.0 --port 8000 --reload
  db:
    container_name: my-food-db
    image: postgres:14
    env_file: .env
    ports:
      - 5432:5432
