apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
data:
  POSTGRES_DB: G9zdGdyZXNkYg==
  POSTGRES_USER: cG9zdGdyZXNhZG1pbg==
  POSTGRES_PASSWORD: YWRtaW4xMjM=
  POSTGRES_HOST: cG9zdGdyZXMtc3Zj
