apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
data:
  POSTGRES_DB: bXlmb29kLWRiCg==
  POSTGRES_USER: bXlmb29kLXVzZXIK
  POSTGRES_PASSWORD: bXlmb29kLXBhc3N3b3JkCg==
  POSTGRES_HOST: cG9zdGdyZXMtc3ZjCg==
