apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
spec:
  storageClassName: manual
  capacity:
    storage: 200M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/minikube/directory/structure/"
    type: DirectoryOrCreate
