"""Add user order relationship

Revision ID: 966b0d48a72f
Revises: 1533bfc72cc5
Create Date: 2023-07-07 08:20:34.773449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "966b0d48a72f"
down_revision = "1533bfc72cc5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("order", sa.Column("user_uuid", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "order", "user", ["user_uuid"], ["uuid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "order", type_="foreignkey")
    op.drop_column("order", "user_uuid")
    # ### end Alembic commands ###
