name: ci-myfood
on:
  pull_request:
    branches:
      - development
      - main
  push:
    branches:
      - main

jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: sudo apt-get update
      - run: sudo apt-get --no-install-recommends --no-upgrade -y install python3-pip
      - run: pip install -r requirements.txt
      - run: pytest --cov-report xml:coverage.xml
      - run: coverage xml coverage.xml
      - name: Get Cover
        uses: orgoro/coverage@v3.1
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          thresholdAll: 0.8
          thresholdNew: 0.9
